declare module "@app";
declare module "@layouts";
declare module "@pages";
declare module "@routes";
declare module "@shared";
declare module "@widgets";
declare module "@widgets/header";
declare module "@styled-system";
declare module "@styled-system/css";
